// generated by Fast Light User Interface Designer (fluid) version 1.0106

#ifndef capcfg_h
#define capcfg_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *capcfgwnd;
#include <FL/Fl_File_Input.H>
extern Fl_File_Input *videodev;
#include <FL/Fl_Input.H>
extern Fl_Input *videochan;
#include <FL/Fl_Slider.H>
extern Fl_Slider *brightness;
extern Fl_Slider *contrast;
#include <FL/Fl_Return_Button.H>
void capture_config();
#endif
