// generated by Fast Light User Interface Designer (fluid) version 1.0106

#ifndef filtercfg_h
#define filtercfg_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *filterswnd;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *grayscale_enabled;
extern Fl_Check_Button *average_enabled;
extern Fl_Check_Button *range_enabled;
Fl_Double_Window* make_filters_wnd();
#endif
