// generated by Fast Light User Interface Designer (fluid) version 1.0106

#ifndef capcfg_h
#define capcfg_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *capcfgwnd;
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Choice.H>
extern Fl_Choice *capdevice;
void capture_config();
#endif
